[workspace]
description = "A Simple accounting LEDGEr, GnuCash inspired and Rust powered."

members = [
    "sledge_config",
    "sledge_model",
    "sledge_server",
    "sledge_services",
    "sledge_store",
    "sledge_tui"
]